# Time settings
NO_TIME = 'no_time'
ABSOLUTE = 'absolute'
BYOYOMI = 'byoyomi'
CANADIAN = 'canadian'
FISCHER = 'fischer'
CUSTOM = 'custom'

VALID_TIME_SETTINGS = [NO_TIME, ABSOLUTE, BYOYOMI, CANADIAN, FISCHER, CUSTOM]

# User actions
USER_LOGIN = 'login'
USER_LOGOUT = 'logout'

USER_ACTIONS = [USER_LOGIN, USER_LOGOUT]

# Challenge actions
CHALLENGE_CREATE = 'new'
CHALLENGE_CANCEL = 'cancel'
CHALLENGE_ACCEPT = 'accept'
CHALLENGE_DECLINE = 'decline'
CHALLENGE_REVISE = 'revise'

CHALLENGE_ACTIONS = [CHALLENGE_CREATE, CHALLENGE_ACCEPT, CHALLENGE_DECLINE, CHALLENGE_REVISE]

# Priority (lowest first)
PRIORITY_CLOCK = 0
PRIORITY_PLAY = 1
PRIORITY_CHALLENGE = 2
SYNC_PRIORITY = 3
PRIORITY_USER = 4
